version: '3.8'

services:
  mysql-test:
    container_name: mysql-auth-tests
    image: mysql:8.4
    command: --authentication_policy=* --log_bin_trust_function_creators=1
    tmpfs:
      - /var/lib/mysql # en RAM
    environment:
      MYSQL_ROOT_PASSWORD: testing_password
      MYSQL_DATABASE: testbench
    ports:
      - "3309:3306"
